name: Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: '16.x'
      - name: yarn install
        run: yarn install
      - name: lint
        run: cd src && yarn run lint .
      - name: test
        run: yarn run test
      - name: build
        run: yarn run build